### ISSUE TITLE
Exception with material design colors

### ISSUE THREAD

**Issue by priyanmuthu** [ButchersBoy/Dragablz#119]
After the latest Windows update, I am getting the below exception:
`            InnerException: 
                 HResult=-2146233086
                 Message=Specified argument was out of the range of valid values.
Parameter name: percentage
                 ParamName=percentage
                 Source=Dragablz
                 StackTrace:
                      at Dragablz.DragablzColors.BlendColor(Color color1, Color color2, Double percentage) in C:\projects\dragablz\Dragablz\DragablzColors.cs:line 60
                      at Dragablz.DragablzColors.GetBalancedWindowGlassBrush() in C:\projects\dragablz\Dragablz\DragablzColors.cs:line 36
                      at Dragablz.DragablzColors..cctor() in C:\projects\dragablz\Dragablz\DragablzColors.cs:line 20`

Changing to the latest dlls makes everything go black for some reason. Any one know the fix for this?

**Comment by campersau** [comment]
I have the same issue after I updated Windows today...

**Comment by campersau** [comment]
Looks like this is related to #88 . I will try to update to a newer Dragablz version and see if it works.

**Comment by campersau** [comment]
Updating Dragablz fixed the issue!
