### ISSUE TITLE
Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by creeveshft** [ButchersBoy/Dragablz#146]
I get this exception when I tear off a Dragablz tab.

**Stack Trace:** 

   at Dragablz.TabablzControl.<>c.<MonitorReentry>b__164_1(TabablzControl tc) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1016
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<JoinIterator>d__37`4.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Dragablz.TabablzControl.MonitorReentry(DragablzDragDeltaEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1032
   at Dragablz.TabablzControl.PreviewItemDragDelta(Object sender, DragablzDragDeltaEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 967

**Target Site** 

{<>f__AnonymousType4`3[Dragablz.TabablzControl,System.Windows.Point,System.Windows.Point] <MonitorReentry>b__164_1(Dragablz.TabablzControl)}

**Comment by ButchersBoy** [comment]
This a sporadic thing?

**Comment by creeveshft** [comment]
yes
