### ISSUE TITLE
Error Closing a tab with no InterTabClient

### ISSUE THREAD

**Issue by melance** [ButchersBoy/Dragablz#33]
I am getting the following error when attempting to close a tab via the built in close button when not using a InterTabClient:

     System.NullReferenceException: Object reference not set to an instance of an object.
    at Dragablz.TabablzControl.RemoveFromSource(Object item) in      c:\projects\dragablz\Dragablz\TabablzControl.cs:line 1015
     at Dragablz.TabablzControl.RemoveItem(DragablzItem dragablzItem) in c:\projects\dragablz\Dragablz\TabablzControl.cs:line 808
    at Dragablz.TabablzControl.CloseItemHandler(Object sender, ExecutedRoutedEventArgs executedRoutedEventArgs) in c:\projects\dragablz\Dragablz\TabablzControl.cs:line 1124
    at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
    at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
    at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
    at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
    at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
    at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
    at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
    at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
    at System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
    at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
    at System.Windows.Controls.Primitives.ButtonBase.OnClick()
    at System.Windows.Controls.Button.OnClick()

**Comment by ButchersBoy** [comment]
Fixed.

**Comment by melance** [comment]
On line 813 of TabablzControl.cs, it errors again with a null reference because InterTabController is null in the if statement.

**Comment by ButchersBoy** [comment]
Apologies, that didn't show up in the little test app I ran.  Deployed a new version.  Can you test and post back the result?

**Comment by melance** [comment]
Looks like it's working now.  Thanks.
