### ISSUE TITLE
Get an unhandled exception in Dragablz code when I tear off tab

### ISSUE THREAD

**Issue by creeveshft** [ButchersBoy/Dragablz#98]
here is the stack trace 

at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.RoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at Dragablz.DragablzItem.ThumbOnDragDelta(Object sender, DragDeltaEventArgs dragDeltaEventArgs) in C:\projects\dragablz\Dragablz\DragablzItem.cs:line 541
   at System.Windows.Controls.Primitives.DragDeltaEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.Thumb.OnMouseMove(MouseEventArgs e)
   at System.Windows.UIElement.OnMouseMoveThunk(Object sender, MouseEventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ButchersBoy** [comment]
Are you running inside a Layout?  It's a null ref exc, right?

**Comment by creeves2** [comment]
Yes its a null reference.   Not sure what you mean by layout.  I have a bunch of user controls inside the tabcontrol.  I am using the mhapps as well. 

It only gives this error some of the time.  It happens when I slowly drag the tab out.  If I quickly move the tab it doesnt happen.

**Comment by ButchersBoy** [comment]
Can you visually see the new window get created before the crash?  Or does it just seem to die immediately?

**Comment by creeves2** [comment]
I see the window get generated. But as I drag it out it freezes, and gives
this exception.

**Comment by creeves2** [comment]
If I drag it out, by dragging it super quickly, not holding the mouse
button down for too long it will work

**Comment by SCKelemen** [comment]
I have the same issue. I can reorder fine, but if I leave the bounding tabheader area, it freezes and crashes. 
![image](https://cloud.githubusercontent.com/assets/4325375/16270765/7216d936-3865-11e6-93ed-558fa83003ee.png)

**Comment by creeveshft** [comment]
This exception happens when I have a tabcontrol inside one of my tabs. I must first visit the tab that contains the tabcontrol, then I can drag them properly. 

If I try to drag the tabs without first visiting the tabcontrol that contains sub-tabs it will give the exception.
Does the tabs do some initialization when they are displayed? Because if I just visit the tab with sub-tabs first, then everything works.

**Comment by SCKelemen** [comment]
@creeveshft  I'll have to test that thought tomorrow.

**Comment by ButchersBoy** [comment]
@SCKelemen ...a lot is happening when you tear out; creating a new window & visual tree, moving the tab content to the new items source.  This invariably involve executing some of your systems code too.  You'll have to post a full stack trace, or even better post a demo repo.

**Comment by SCKelemen** [comment]
@ButchersBoy  it started working again for me. It seems like it might be a race condition. I'll look into it more, when I can reliably reproduce the error.

**Comment by creeveshft** [comment]
I was able to fix this error by adding

`   <Window.Resources>
       
                <dragablz:InterTabController x:Key="InterTabController" x:Shared="False" />
                <Style TargetType="dragablz:TabablzControl" BasedOn="{StaticResource {x:Type dragablz:TabablzControl}}">
                    <Setter Property="IsTabStop" Value="False" />
                    <Setter Property="Focusable" Value="False" />
                    <Setter Property="HeaderMemberPath" Value="Name" />
                    <Setter Property="BorderThickness" Value="0" />
                    <Setter Property="InterTabController" Value="{StaticResource InterTabController}" />
                </Style>
           
    </Window.Resources>`


**x:Shared = false** fixed the issue for me, also I updated to the latest NuGet package :)
